### ISSUE TITLE
New Endpoint for returning checklists at the Asset level, vs Asset-STIG level.

### ISSUE THREAD

**Issue by cd-rite** [NUWCDIVNPT/stig-manager#170] opened 2021-02-27 22:19 UTC

**Comment by csmig** [comment] 2021-03-31 11:13
@cd-rite Is this a duplicate of #169 ?

**Comment by csmig** [comment] 2021-05-04 13:07
@cd-rite Bumping, assuming this is a duplicate of #169, and closing

**Closed by csmig** 2021-05-04 13:07 UTC
Labels: API, enhancement
