### ISSUE TITLE
STIG Manager on remote hosts

### ISSUE THREAD

**Issue by falie-arch** [NUWCDIVNPT/stig-manager#1352] opened 2024-08-23 21:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [ ] UI or other client
- [X] Deployment
- [ ] Elsewhere

### Current Behavior

This is a similar issue to[ #393](https://github.com/NUWCDIVNPT/stig-manager/issues/393). I'm trying to run STIG Manager on a server and access it by other hosts. I followed the same guide linked on #393 on dockerhub with the three containers but with podman-compose instead. It runs on the server, but it can't be accessed by other hosts - visiting http://IP_ADDRESS:54000 keeps loading until it times out. STIG Manager doesn't come up at all; it's the page itself that's loading. I tried the suggestions on #393, like modifying the .yml file to set the envar with the server IP address and also adding TCP ports 54000 and 8080 to the firewall on the server, but they didn't work. I can access keycloak at http://IP_ADDRESS:8080.

### Describe your Environment

```markdown
- Hosting:
- Browser:Chrome
- OS:RHEL8
- Node:
- npm:
```

**Comment by cd-rite** [comment] 2024-08-25 17:49
Hi @falie-arch If you can successfully load the app on the server it is deployed on, then the issue is most likely elsewhere in your configuration (firewall, compose file, etc. ).
The STIG Manager UI does require a [secure context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts) in order to be used remotely, but usually you would see a message explaining this when first loaded. If you see nothing when you go to the appropriate URL, then the issue may still be with your firewall or some other configuration. **However, you still won't be able to use the UI remotely without further configuration, such as adding a proxy to handle https connections.** 

We have a sample orchestration that uses a proxy that may help you get set up. This sample uses self-signed certificates that are imported into the browser for the demo, but to access remotely you would need to provide certificates that would be trusted by the remote clients (ie. DoD-signed certs, if you are in that environment):
https://github.com/NUWCDIVNPT/stigman-orchestration

Since this issue seems to be related to environmental/configuration factors rather than a bug in our application, you may have better luck asking for help or seeing if anyone has had a similar issue in our discussion forums. We also try to participate in troubleshooting there:
https://github.com/NUWCDIVNPT/stig-manager/discussions
for example:
https://github.com/NUWCDIVNPT/stig-manager/discussions/1266

I'll close the issue for now, but feel free to reopen it if further troubleshooting points towards an issue with the application itself.

**Closed by cd-rite** 2024-08-25 17:49 UTC
