### ISSUE TITLE
Error Updating V-17849 in Network_-_Other_Devices-V8R23

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#1010] opened 2023-05-31 13:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest version of STIG Manager?

- [X] I am using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases).
- [ ] I am NOT using the latest [Release](https://github.com/NUWCDIVNPT/stig-manager/releases). I am aware that the first thing I will be asked to do is update the application so that I have the latest bugfixes.

### Where are you experiencing the issue?

- [ ] API
- [X] UI or other client
- [ ] Deployment
- [ ] Elsewhere

### Current Behavior

When trying to update the result a/o detail a/o comment for V17849 in STIG Network_-_Other_Devices-V8R23 I receive an error.
I have tried making changes manually in the GUI, using the batch edit and by importing a CKL with the required updates. 

As error logs contain details about the implementation and device configuration the errors can be provided to the development team via email.

### Expected Behavior

That updates can be made to check.

### Can you provide screenshots, logs, or other useful artifacts?

As error logs contain details about the implementation and device configuration the errors can be provided to the development team via email.

### Describe your Environment

```markdown
- Hosting:
- Browser:
- OS:
- Node:
- npm:
```

**Comment by cd-rite** [comment] 2023-07-05 20:52
Unable to reproduce with latest version.
User resolved by re-importing Network_-_Other_Devices-V8R23 STIG

**Closed by cd-rite** 2023-07-05 20:52 UTC
