### ISSUE TITLE
FEATURE REQUEST:  Is there a way to carry over the history from previous scans?

### ISSUE THREAD

**Issue by SmithR49** [NUWCDIVNPT/stig-manager#1443] opened 2024-12-04 16:00 UTC
I am curious if there is a way to reupload the same scans and have findings that were found to "Need Review" to keep their history or details?

**Comment by cd-rite** [comment] 2024-12-10 21:12
I believe this is a duplicate of https://github.com/NUWCDIVNPT/stig-manager/issues/1445
The response there should apply to this situation: https://github.com/NUWCDIVNPT/stig-manager/issues/1445#issuecomment-2532898833

**Closed by cd-rite** 2024-12-10 21:12 UTC
Labels: enhancement
