### ISSUE TITLE
FEATURE REQUEST: Treat Evaluate STIG Findings as Automated

### ISSUE THREAD

**Issue by mayszs** [NUWCDIVNPT/stig-manager#586] opened 2022-02-23 12:38 UTC
**Is your feature request related to a problem? Please describe.**
Much like Benchmark Scans Evaluate STIG is an automated tool but checks performed by Evaluate STIG are treated like a manual check requiring each to be reviewed, submitted and approved. On a small scale deployment this may not appear to be an issue but for systems with asset counts in the thousands this consumed a lot of time.

**Describe the solution you'd like**
For any check with a status of NF or NA where EvaluateSTIG is listed in the CKL Finding Details the check should be considered an automated check and should automatically be imported as approved.
For any check with a status of NF or NA where EvaluateSTIG is listed in the CKL Finding Details the check should be considered an automated check and imported with an Open Status.

**Describe alternatives you've considered**
With EvaluateSTIG completing 80% or more of the checks in any given STIG the only way to utilize the tracking and reporting functions in STIGMan effectively require all of these to be submitted and reviewed individually which is an inefficient use of labor hours.

**Additional context**

**Comment by dtester1** [comment] 2022-02-23 18:53
I didn't realize there was a ticket in for this as I just looks like I created the same issue.  Its not not a finding period that we are suggesting.  Its only approving ones that are NF that have no manual interaction from answer files.

**Comment by cd-rite** [comment] 2022-02-23 20:41
Additional info in #588, closed as duplicate of this issue.

**Comment by csmig** [comment] 2022-02-23 20:55
Currently there are challenges 1) identifying when EvalSTIG is the source of a review and 2) knowing when an Answer file was used. @cd-rite and I are scheduled to meet with the EvalSTIG team next week. We'll chat about ways do that.

Once we can identify the review tool and context, we will consider how to use that info in the STIG Manager review workflow (saved -> submitted -> accepted/rejected).

**Comment by cd-rite** [comment] 2022-02-23 20:56
FYI, we will be starting a series of discussions with the Eval STIG team to further RMF tool interoperability.  One of our topics of discussion will definitely be how to treat Eval STIG results, given our concerns about the integrity of its generated .ckl files.  

From our point of view, anyone could open up a .ckl file and enter an "Evaluate STIG" prefix into a comment field, and we need a way to determine what the true source was if we are to give those results special treatment.  This could involve getting Eval STIG to directly submit results to STIGMan, rather than going through intermediate .ckl files, or having them digitally sign bundles of their output. 

This area will evolve!

**Comment by mayszs** [comment] 2022-02-23 21:53
There is no more guarantee of scan integrity using SCAP anymore than there is with a CKL generated by EvaluateSTIG as someone could just as easily open an XCCDF file and edit the results using any text editor.

**Comment by csmig** [comment] 2022-02-23 22:55
Agreed, there's no suggestion otherwise above. The integrity issue is present for both formats. However, XCCDF does offer the element `<xccdf:signature>` for digital signing the content.

I suspect we will settle on an approach that involves changes in both EvalSTIG and STIG Manager Watcher, and adds the notion of trusted service accounts to the STIG Manager API. Distinctions between CKL and XCCDF is not likely to affect this. Watcher processes both.

**Comment by cd-rite** [comment] 2022-05-17 05:59
Resolved in PR #659, which provides users with granular control over the status of imported Reviews.

**Closed by cd-rite** 2022-05-17 05:59 UTC
Labels: enhancement
